version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kiosk-postgres
    restart: always
    environment:
      POSTGRES_USER: aommykung
      POSTGRES_PASSWORD: 1250Za
      POSTGRES_DB: kiosk_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
